name: ct-macos

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-11

    strategy:
      matrix:
        compiler: [clang++-9, clang++-11, clang++-12, clang++-13, clang++-14]
        cpp_version: [c++14, c++17, c++20]

    steps:
      - uses: actions/checkout@v3

      - name: Setup clang
        run: |
          VERSION=$(echo ${{matrix.compiler}} | sed 's/clang++-//g')
          brew install llvm@${VERSION}
        if: ${{ startsWith(matrix.compiler, 'clang++') }}

      - name: Test
        run: |
          export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
          VERSION=$(echo ${CXX} | sed 's/^clang++-//g')
          export CXX=clang++
          export CC=clang
          export PATH="/usr/local/opt/llvm@i${VERSION}/bin:${PATH}"
          export LDFLAGS="-L/usr/local/opt/llvm@${VERSION}/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm@${VERSION}/include:${CPPFLAGS}"
          echo CC=${CC}/CXX=${CXX}/BAZEL_CXXOPTS=${BAZEL_CXXOPTS}
          bazelisk test :komoperm_test
        env:
          CXX: ${{ matrix.compiler }}
          BAZEL_CXXOPTS: ${{'-std='}}${{ matrix.cpp_version }}

  # This job is used for status check. It becomes success iff all of the above
  # jobs returned success.
  check-macos:
    runs-on: macos-11
    needs: build-macos
    steps:
      - name: Check Build Status
        run: echo 'Done'
